language: generic
env:
  global:
    - CLI_VERSION=master
  matrix:
    - BOARD="esp32:esp32:heltec_wifi_lora_32_V2"
    - BOARD="esp32:esp32:t-beam"
before_install:
  - git submodule update --init --recursive
  - curl https://raw.githubusercontent.com/arduino/arduino-cli/${CLI_VERSION}/install.sh | sh
  - export PATH=$PATH:$PWD/bin/
  - arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  - if [[ "$BOARD" =~ "esp32:esp32:" ]]; then
      arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json;
    fi
  - buildExampleSketch() { arduino-cli compile -v -t -b $BOARD $PWD/examples/$1/$2/$2.ino; }
script:
  - buildExampleSketch 1.Ducks MamaDuck
  - if [[ "$BOARD" != "esp32:esp32:t-beam" ]]; then
      buildExampleSketch 4.Ble-Duck-App Ble-Duck-App;
    fi