language: generic
env:
  global:
    - CLI_VERSION=master
  matrix:
    - BOARD="esp32:esp32:heltec_wifi_lora_32_V2"
    - BOARD="esp32:esp32:t-beam"
before_install:
  - git submodule update --init --recursive
  - curl https://raw.githubusercontent.com/arduino/arduino-cli/${CLI_VERSION}/install.sh | sh
  - export PATH=$PATH:$PWD/bin/
  - arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  - if [[ "$BOARD" =~ "esp32:esp32:" ]]; then
      arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json;
    fi
  - arduino-cli core update-index --enable_unsafe_install true
  - arduino-cli lib install --git-url https://github.com/contrem/arduino-timer.git
  - arduino-cli lib istall --git-url https://github.com/jgromes/RadioLib.git

  - buildExampleSketch() { arduino-cli compile -v -t -b $BOARD $PWD/examples/$1/$2/$2.ino; }
script:
  - buildExampleSketch 1.Ducks DuckLink
  - buildExampleSketch 1.Ducks MamaDuck
  - buildExampleSketch 1.Ducks PapaDuck
  - buildExampleSketch 1.Ducks DetectorDuck
  - buildExampleSketch 2.Custom-MamaDuck-Example
  - buildExampleSketch 3.Sensor-Examples BMP180Example
  - buildExampleSketch 3.Sensor-Examples BMP280Example
  - buildExampleSketch 3.Sensor-Examples DHT11Example
  - buildExampleSketch 3.Sensor-Examples DustSensorExample
  - buildExampleSketch 3.Sensor-Examples MQ7Example
  - buildExampleSketch 3.Sensor-Examples WS287Example
  - if [[ "$BOARD" != "esp32:esp32:t-beam" ]]; then
      buildExampleSketch 4.Ble-Duck-App Ble-Duck-App;
    fi
  - buildExampleSketch 5.Papa-Iridium-Example Papa-DishDuck
  - buildExampleSketch 5.Papa-Iridium-Example Papa-DishDuck-WiFi
  - buildExampleSketch 6.PaPi-DMS-Lite-Examples Serial-PaPiDuckExample
  - buildExampleSketch 6.PaPi-DMS-Lite-Examples Wifi-PaPiDuckExample
  - if [[ "$BOARD" != "esp32:esp32:heltec_wifi_lora_32_V2" ]]; then
      buildExampleSketch 7.TTGO-TBeam-Examples TTGO-APX-Examples;
    fi
  - if [[ "$BOARD" != "esp32:esp32:heltec_wifi_lora_32_V2" ]]; then
      buildExampleSketch 7.TTGO-TBeam-Examples TTGOGPSExample;
    fi
