name: Documentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: Ender-events/pandoc@master
        with: 
          args: "--resource-path=doc -f markdown-implicit_figures doc/howToBuildADuck.md --pdf-engine=xelatex  -V \"mainfont:DejaVu Sans\" -V \"geometry: left=2cm,right=2cm,top=3cm,bottom=3cm\" -o output/howToBuildADuck.pdf"
      - uses: docker://michaelperrin/pdfunite:0.48.0
        with:
          args: "doc/assets/pdfs/title.pdf output/howToBuildADuck.pdf output/final.pdf"
      - run: rm output/howToBuildADuck.pdf
      - run: mv output/final.pdf doc/How\ to\ build\ a\ duck.pdf
      - run: rm -rf output
      - uses: actions/upload-artifact@master
        with:
          name: doc
          path: doc/How\ to\ build\ a\ duck.pdf
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}