name: Build examples

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [-c ./examples/DuckLinkExample/platformio.ini ./examples/DuckLinkExample/,
                  -c ./examples/MamaDuckExample/platformio.ini ./examples/MamaDuckExample/,
                  -c ./examples/PapaDuckExample/platformio.ini ./examples/PapaDuckExample/]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        platformio lib -g install file://.

    - name: Build
      run: platformio ci --lib="." ${{ matrix.example }}
